Features : Weather app
Fanger53/weather-app pull request #1
Opened 2021-05-17 21:51 UTC by Fanger53

# Weather App
 this app consist use an API to get information about the weather from a specific place
## in this project, I use the next technologies : 
- Html
- Scss
- javascript
- Webpack
- API from open weather map

2021-05-18 01:05 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑**

Hello @Fanger53 
Great job on this project. I can tell you put it in a lot of work. 
Great job on the background gradient.

However, some changes are requested to get it approved.

[REQUIRED]: Kindly add `"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
` to package.json. This will allow you to run commands like npm start to get the app running.

[REQUIRED]: In weather.js, kindly use arrow function.

[REQUIRED]: Add a toggle button to change from celsius to fahrenheit

[REQUIRED]: The UI changes its appearance based on the received data.

[OPTIONAL]: it fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location  

[OPTIONAL]: it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API

That's it.🙏

Make the requested changes and ask for another review👍👌

Happy coding💻💻💻

2021-05-18 16:36 UTC, Fanger53 commented
its a nice feature but it's not necessary I like how looks de Celsius and Fahrenheit at the same time 
[REQUIRED]: Add a toggle button to change from celsius to Fahrenheit THIS is optional is not a requirement

2021-05-18 17:59 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  -  Follows gitwork-flow. 💯
  -  App is functional and available online. 💯 

- ### To Improve
  
  - [ ] [MANDATORY] As the previous reviewer mentioned, you must have a toggle control to determine if the result will be shown in Celsius or Fahrenheit ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
  - [ ] [MANDATORY] It must change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
      - Example: if the weather is cloudy or rainy, it should change the background accordingly.

  NOTE: Those features are **MANDATORY**!    
  
_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-05-21 23:12 UTC, Forison approved these changes
# Status::Approved✔️ 

#### Good job on addressing the issue raised in the previous review, the application changes appearance based on result and we are able to view temperature in both required units😇.

**[Optional because it wasn't mentioned earlier, but very important and a mandatory requirement]**

* [ ] Let's display an error to the user when the wrong city or country in entered in the search field, currently errors are logged in the console but not information is seen by the user on the front-end. Check associated comments below👇.

**[Optional]**

- [ ]  it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))

 - [ ] it fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location
#### Happy coding

Addo Forison

2021-05-21 23:12 UTC, Forison commented on src/modules/weather.js
> +    const response = await fetch(apiUrl, { mode: 'cors' });
* [ ] It has error handling for `promises` or `async/await` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
* Let us use `try and catch` block, based on this we can display error on the UI when the data fetching fails as mention above.

2021-05-22 14:14 UTC, merged